# Generated by Django 4.1.5 on 2023-01-18 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watch_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='listing_watch_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
